-- Content schema (generated by scripts/build_masail.py from data/masail/*.yaml).
-- Stable keys:  masala "2-021" · reading "2-021#1" · mawdi "2-021@2:61:5" (masala@sura:aya:word)

CREATE TABLE meta   (key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE qurra  (name TEXT PRIMARY KEY, ord INTEGER);
CREATE TABLE rawis  (name TEXT PRIMARY KEY, qari TEXT REFERENCES qurra(name), ord INTEGER);

CREATE TABLE matn   (n INTEGER PRIMARY KEY, bab TEXT, sadr TEXT, ajz TEXT, plain TEXT);

CREATE TABLE masail (
  id TEXT PRIMARY KEY, naw TEXT, bab TEXT, abyat TEXT, kalima TEXT, kalima_plain TEXT, nitaq TEXT,
  qawl TEXT, rumuz TEXT, natija TEXT, note TEXT, review TEXT, adad INTEGER, src_file TEXT,
  marji TEXT,                          -- summary of the sources the ruling was settled on (see table marji)
  iqrar TEXT,                          -- summary of the reviewer's own decisions (see table iqrar) — not a source
  tahrir TEXT);                        -- kinds of tahrir notes on this masala (see table tahrir)
CREATE TABLE masala_abyat (masala_id TEXT REFERENCES masail(id), bayt INTEGER REFERENCES matn(n));

-- مصدر الاعتماد: the source each ruling / review decision was settled on
CREATE TABLE marji (
  masala_id TEXT REFERENCES masail(id), ord INTEGER,
  kitab TEXT,    -- الوافي | الإضاءة | ... (a book, never a personal decision)
  safha TEXT, mawdu TEXT, man TEXT, tarikh TEXT);
CREATE INDEX ix_marji ON marji(masala_id);

-- إقرار المراجع: the reviewer's own decisions (kept apart from the sources)
CREATE TABLE iqrar (masala_id TEXT REFERENCES masail(id), ord INTEGER, man TEXT, tarikh TEXT, mawdu TEXT);
CREATE INDEX ix_iqrar ON iqrar(masala_id);

-- تحريرات وتنبيهات: خروج عن الطريق | وجه ضعيف | ليس عليه العمل | زيادة على النظم | تنبيه على العبارة
CREATE TABLE tahrir (
  masala_id TEXT REFERENCES masail(id), ord INTEGER, naw TEXT,
  rawi TEXT,     -- who it concerns (names as in readings), optional
  bayan TEXT,    -- what the nazm says / the added wajh / what is meant
  hukm TEXT,     -- e.g. «لا يقرأ به»
  qawl TEXT,     -- the verifiers' wording (short)
  kitab TEXT, safha TEXT);
CREATE INDEX ix_tahrir ON tahrir(masala_id);
CREATE INDEX ix_tahrir_naw ON tahrir(naw);

-- one row per reading as defined in YAML (who reads it and how)
CREATE TABLE readings (
  rid TEXT PRIMARY KEY, masala_id TEXT REFERENCES masail(id), ord INTEGER, by_text TEXT,
  lafz TEXT, tahwil TEXT, wasf TEXT, hal TEXT, dalil TEXT, ramz TEXT,
  ziyada INTEGER NOT NULL DEFAULT 0);  -- 1 = a wajh added by the verifiers beyond the nazm (زيادة على النظم)
CREATE TABLE reading_rawis (rid TEXT REFERENCES readings(rid), rawi TEXT REFERENCES rawis(name));

CREATE TABLE mawadi (
  mid TEXT PRIMARY KEY, masala_id TEXT REFERENCES masail(id), sura_no INTEGER, sura TEXT,
  aya_no INTEGER, word_no INTEGER, mawdi TEXT, mawdi_plain TEXT, aya TEXT, aya_voc TEXT);

-- materialized: موضع × راوٍ × وجه
CREATE TABLE qiraat (
  mid TEXT REFERENCES mawadi(mid), rid TEXT REFERENCES readings(rid), rawi TEXT REFERENCES rawis(name),
  lafz TEXT, lafz_plain TEXT, wajh TEXT, hafs INTEGER);

CREATE INDEX ix_q_rawi ON qiraat(rawi);
CREATE INDEX ix_q_mid  ON qiraat(mid);
CREATE INDEX ix_w_pos  ON mawadi(sura_no, aya_no, word_no);
CREATE INDEX ix_w_m    ON mawadi(masala_id);
CREATE INDEX ix_ab     ON masala_abyat(bayt);

-- flat view (used by scripts/riwaya.py and exports)
CREATE VIEW qiraat_v AS
SELECT q.mid, q.rid, q.rawi, r.qari, w.sura_no, w.sura, w.aya_no, w.word_no, w.mawdi, w.aya,
       q.lafz, d.wasf, d.hal, q.wajh, CASE q.hafs WHEN 1 THEN 'نعم' ELSE 'لا' END AS hafs,
       m.id, m.naw, m.bab, m.abyat, d.dalil, d.ramz, m.note, m.review, m.marji, m.iqrar, m.tahrir, d.ziyada
FROM qiraat q JOIN mawadi w ON w.mid = q.mid JOIN readings d ON d.rid = q.rid
JOIN masail m ON m.id = w.masala_id JOIN rawis r ON r.name = q.rawi;
